#!/bin/bash
#SBATCH --job-name=snekBSCO
#SBATCH --output=/scratch/mib75/snakemake_tutorials/busco_snakemake/snakemake_jobscripts.out
#SBATCH --mem=36000
#SBATCH -c 24
#SBATCH --time=36:00:00
#SBATCH --mail-user=michael.byars@nau.edu
#SBATCH --mail-type=ALL
#SBATCH --export=ALL

module load anaconda3
source activate snakemake

cd /scratch/mib75/snakemake_tutorials/busco_snakemake

srun snakemake --use-conda --cores 24 

